### ISSUE TITLE
Trouble loading model

### ISSUE THREAD

**Issue by 1uciusy** [castacks/tartan_drive#2]
Hi, I find your dataset very helpful for my research and I want to learn more detailed implementation of your work.

But I have some trouble load your models, when I run code like
```Python3
torch.load("./models/rgb/model.cpt")
```
It tells me `ModuleNotFoundError: No module named 'wheeledsim_rl'`. And I'm stuck here, having no idea where to find/install this module.
Hope you may have a solution and help me.

Thanks
Lucius.

**Comment by LuZhouyu1** [comment]
I encountered the same issue. Have you managed to resolve it?

**Comment by 1uciusy** [comment]
Emmm by writing an email and getting no response..

**Comment by striest** [comment]
sorry - wheeledsim_rl is now added to the repo and updated steps are included in README

**Comment by 1uciusy** [comment]
Many thanks!
