### ISSUE TITLE
Meaning of N_per_step option

### ISSUE THREAD

**Issue by kajananchinniah** [castacks/tartan_drive#3]
Hi @striest,

I had a quick question regarding the `N_per_step` option. I'm using the `2021_atv_3.yaml` spec with `use_vel` set to `True`.

I was wondering how should this option be interpreted. For example, when it's set to 20, I noticed each observation would have 20 datapoints per a timestep. Would this be 20 timesteps stacked together (e.g. 2 s of readings stacked together) or would it be 20 samples from within a particular timestep (e.g. 20 readings that took less 0.1 s to obtain) ? 

Thanks!

**Comment by striest** [comment]
second interpretation - N_per_step divides a model step, i.e. 20 readings would be at 200Hz
