### ISSUE TITLE
How to download a dataset? 

### ISSUE THREAD

**Issue by xzxzmmnn** [castacks/tartan_drive#6]
I have attempted to download the dataset as per the provided instructions, however, it seems to be unsuccessful. It appears that the link to the dataset may be broken. Could you guide me on the correct procedure to download a dataset?

**Comment by ccsmm78** [comment]
Me too.  
I'm not able to access the url 'http://airlab-share.andrew.cmu.edu' as well as http://airlab-share.andrew.cmu.edu/dataset-icra22/20210826_heightmaps_1.tar.gz

I've visited here from https://theairlab.org/tartandrive-dataset/

**Comment by deavn2236** [comment]
According to the provided http://airlab-share.andrew.cmu.edu/dataset-icra22 I am unable to download the dataset with the corresponding URL and file number. Have you been successful

**Comment by Amigoshan** [comment]
We just moved the data to a new server! Please check the new script. Sorry for the inconvenience!
